// Generated by psc-bundle 0.7.6.1
var PS = { };
(function(exports) {
  /* global exports, console */
  "use strict";

  // module Control.Monad.Eff.Console

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
 
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Prelude"];
  var $dollar = function (f) {
      return function (x) {
          return f(x);
      };
  };                                                
  var flip = function (f) {
      return function (b) {
          return function (a) {
              return f(a)(b);
          };
      };
  };
  exports["flip"] = flip;
  exports["$"] = $dollar;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Control.Monad.Eff.Console"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  exports["log"] = $foreign.log;;
 
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  // module Immutable.Map

  var mod = require('immutable').Map;

  exports.mod = mod;

  // exports.empty = mod.empty;

  exports.empty = function () { return mod.Map({"foo":"bar"}); };
 
})(PS["Immutable.Map"] = PS["Immutable.Map"] || {});
(function(exports) {
    

  exports.unsafeShow = function (obj) {
    return String(obj);
  };                                          
 
})(PS["Immutable.Utils"] = PS["Immutable.Utils"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Immutable.Utils"];
  var Data_Function = PS["Data.Function"];
  var Data_Maybe = PS["Data.Maybe"];
  exports["unsafeShow"] = $foreign.unsafeShow;;
 
})(PS["Immutable.Utils"] = PS["Immutable.Utils"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Immutable.Map"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Function = PS["Data.Function"];
  var Data_Monoid = PS["Data.Monoid"];
  var Immutable_Utils = PS["Immutable.Utils"];
  exports["empty"] = $foreign.empty;;
 
})(PS["Immutable.Map"] = PS["Immutable.Map"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];
  var Immutable_Map = PS["Immutable.Map"];
  var Immutable_Utils = PS["Immutable.Utils"];     
  var $bar$greater = Prelude.flip(Prelude["$"]);
  var store = Immutable_Map.empty;
  var main = $bar$greater(Immutable_Utils.unsafeShow(store))(Control_Monad_Eff_Console.log);
  exports["main"] = main;
  exports["store"] = store;
  exports["|>"] = $bar$greater;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
